# Generated by Django 3.0.1 on 2019-12-20 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intreped', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cumulative_time', models.CharField(max_length=10)),
                ('badge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intreped.Badge')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intreped.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='badges',
            field=models.ManyToManyField(through='intreped.TeacherBadge', to='intreped.Badge'),
        ),
    ]
