# Generated by Django 3.0.1 on 2020-01-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intreped', '0003_auto_20200106_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='category',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='teacherbadge',
            unique_together={('teacher_id', 'badge_id')},
        ),
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together={('teacher_id', 'course_id')},
        ),
    ]
